tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "cloudfoundry/tap"

# Microsoft Azure CLI 2.0
brew "azure-cli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat" 
# Encoding tool
brew "ffmpeg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Distributed revision control system
brew "git"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Platform built on V8 to build network applications
brew "node"
# Programatically correct mistyped console commands
brew "thefuck"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
#Cloud Foundry CLI
brew "cloudfoundry/tap/cf-cli"